#!/bin/bash

if [ $# -ne 1 ]; then
  echo "Usage:"
  echo "$0 <branch>"
  echo "$0 <branch> <sub-domain|full-domain>"
  echo "$0 <branch> <sub-domain|full-domain> <login:pass>"
  exit 1
fi

branch=$1
domain=$2
password=$3
projectName=$USER
userDir="/home/$USER"

if [ -n "$password" ] && [ -z "$domain" ]; then
  echo "Password option can only be set if domain is set."
fi

# Ensure script is run from a user directory
if [[ $PWD != $userDir ]]; then
  echo "Script must be run from a project user root."
  exit 1
fi

# Create variables
dataDir="$userDir/data"
tarFile="$userDir/artifacts/$branch.tar.gz"
buildNumber=$(openssl rand -hex 8)
destinationBuildDir="$userDir/builds/$branch-$buildNumber"
destinationBranchLink="$userDir/branches/$branch"

# Extract tar.gz file
if [ ! -f "$tarFile" ]; then
  echo "File $tarFile not found"
  exit 1
fi
mkdir -p $destinationBuildDir
if ! tar -xzf $tarFile -C $destinationBuildDir; then
  echo "Failed to extract $tarFile"
  rm -f $tarFile
  exit 1
fi

# Move pasta docker compose file
if [ -f "$destinationBuildDir/docker-compose.pasta.yaml" ]; then
  mv "$destinationBuildDir/docker-compose.pasta.yaml" "$destinationBuildDir/docker-compose.yaml"
fi

# No docker compose file
if [ ! -f "$destinationBuildDir/docker-compose.yaml" ]; then
  echo "No docker-compose.yaml or docker-compose.pasta.yaml file found in $tarFile"
  exit 1
fi

# Dot env
dotEnv="$destinationBuildDir/.env"
echo "" >> $dotEnv

# Force pasta project name
sed -i '/^PASTA_PROJECT_NAME=/d' $dotEnv
echo "PASTA_PROJECT_NAME=$projectName" >> $dotEnv

# Inject build number
echo "PASTA_BUILD=$buildNumber" >> $dotEnv

# If we have a domain to set
if [ -n "$domain" ]; then
  # Remove virtual host from dot env
  sed -i '/^VIRTUAL_HOST=/d' $dotEnv
  # Has a dot, it's a full-domain
  # No dot, it's a sub-domain
  if [[ "$domain" != *"."* ]]; then
    domain="$domain.$PASTA_DOMAIN"
  fi
  echo "VIRTUAL_HOST=$domain" >> $dotEnv
  # Setup password ( or remove it ) and reload proxy
  if [ -n "$password" ]; then
    project-password $domain $password
    proxy-reload
  fi
# No domain to set, but no domain in dot env, use auto mode
elif ! grep -q '^VIRTUAL_HOST=' $dotEnv; then
  domain="$projectName-$branch.$PASTA_DOMAIN"
  echo "Missing VIRTUAL_HOST from .env file. Setting domain to $domain"
  echo "VIRTUAL_HOST=$domain" >> $dotEnv
  exit 1
fi

# Set the docker compose project name from the unique build number
# With this, "docker compose" commands can be ran from the branch link and the build directory
composeProjectName="$USER_$branch_$buildNumber"
echo "COMPOSE_PROJECT_NAME=$composeProjectName" >> $dotEnv

# Preparing data directories
echo "Extracting data directories ..."
dockerComposeConfig=$(cd $destinationBuildDir && docker compose config)
dataVolumes=$(echo "$dockerComposeConfig" | grep "source: $HOME/data" | awk -F"$HOME/data" '{print $2}' | tr -d ' ')

# Create directories for each volume
for volume in $dataVolumes; do
  echo "- $volume"
  mkdir -p "${dataDir}${volume}"
done

# FIXME : Maybe find something else than 777 ?
# FIXME : Adding user to the group is not enough for 776, why ?
#echo "USER_ID=$(id -u $USER):$(id -g $USER)" >> $dotEnv
# ADD : usermod -aG www-data $username
# REMOVE : gpasswd -d $username www-data
echo "Patching user on data ..."
chown -R "$USER:$USER" $dataDir
chmod -R 0777 $dataDir

# Docker compose up
echo "Starting containers ..."
if ! (cd $destinationBuildDir && docker compose build && docker compose up -d); then
  echo "⚠ Unable to start docker stack"
  rm -rf $destinationBuildDir
  rm -f $tarFile
  exit 1
fi
echo ""

# TODO : Wait enough time to have the new container ready before stopping the old one
# TODO : Maybe having a heartbeat call or something ?
# TODO : If more than 60s, docker compose down and fail
sleep 3

echo "Stopping and removing old containers ..."
if [ -d $destinationBranchLink ]; then
  oldBranchDir=$(readlink -f $destinationBranchLink)
  (cd $oldBranchDir && docker compose down && docker container prune -f)
  rm -rf $oldBranchDir
fi
echo ""

echo "Creating branch link ..."
ln -sf $destinationBuildDir $destinationBranchLink
rm -f $tarFile

echo ""
echo "Done"
