#!/bin/bash

clear
cd ~
read -p "Enter the project name: " projectName
username="$projectName"
userProjectRoot="/home/$projectName"
rootProjectRoot="$HOME/containers/projects/$projectName"

# Check if this project or user already exists
if [ -d "$userProjectRoot" ]; then
  echo "Project $projectName already exists."
  exit 1
fi
if id "$projectName" &>/dev/null; then
  echo "User $projectName already exists."
  exit 1
fi

# Create a new linux user associated to this project workspace
echo "Creating user $username ..."
adduser --disabled-password --gecos "" $username > /dev/null 2>&1

# Create the project directory structure
echo "Creating project directories ..."
mkdir -p $userProjectRoot/{artifacts,builds,branches,data,.ssh}
# Link workspace into root containers directory
mkdir -p "$rootProjectRoot/keys"
# Generate SSH key pair
echo "Creating SSH keypair ..."
ssh-keygen -t ed25519 -f "$rootProjectRoot/keys/id_ed25519" -N "" > /dev/null 2>&1
# Add the public key to the user's authorized_keys
cat "$rootProjectRoot/keys/id_ed25519.pub" >> "$userProjectRoot/.ssh/authorized_keys"
#
chown -h -R $username:$username $userProjectRoot
chmod 770 -R $userProjectRoot
chmod 700 $userProjectRoot/.ssh
chmod 600 $userProjectRoot/.ssh/authorized_keys

ln -s "$userProjectRoot" "$rootProjectRoot/project"

echo ""
echo "Project $projectName created ✨"