#!/bin/bash

clear
cd ~
read -p "Enter the project name: " projectName
username="$projectName"
userProjectRoot="/home/$projectName"
rootProjectRoot="$HOME/containers/projects/$projectName"

# Check if this project or user already exists
if [ -d "$userProjectRoot" ]; then
  echo "Project $projectName already exists."
  exit 1
fi
if id "$projectName" &>/dev/null; then
  echo "User $projectName already exists."
  exit 1
fi

# Create a new linux user associated to this project workspace
echo "Creating user $username ..."
adduser --disabled-password --gecos "" $username > /dev/null 2>&1

# Allow this user to use Docker
usermod -aG docker $username

echo "Creating project directories ..."
mkdir -p $userProjectRoot/{.config,artifacts,builds,branches,data,.ssh}

echo "Creating SSH keypair ..."
mkdir -p "$rootProjectRoot/keys"
ssh-keygen -t ed25519 -f "$rootProjectRoot/keys/id_ed25519" -N -y "" > /dev/null 2>&1
cat "$rootProjectRoot/keys/id_ed25519.pub" >> "$userProjectRoot/.ssh/authorized_keys"

echo "Copying pasta config into user directory ..."
cp -r "$HOME/.config/pasta" "$userProjectRoot/.config/"

echo "Configuring directories access ..."
chown -h -R $username:$username $userProjectRoot
chmod 770 -R $userProjectRoot
chmod 700 $userProjectRoot/.ssh
chmod 600 $userProjectRoot/.ssh/authorized_keys

echo "Creating shortcut in containers directory ..."
ln -s "$userProjectRoot" "$rootProjectRoot/project"

echo "Create .bashrc for project user ..."
rm -rf "$userProjectRoot/.bash_logout"
cp "$HOME/.bashrc" > $userProjectRoot/.bashrc

echo ""
echo "Project $projectName created ✨"
echo ""
cat "$rootProjectRoot/keys/id_ed25519"