#!/bin/bash

if [ $# -ne 1 ]; then
  echo "Usage:"
  echo "$0 <branch>"
  echo "$0 <branch> --domain <sub-domain|full-domain>"
  echo "$0 <branch> --domain <sub-domain|full-domain> --password <login:pass>"
  exit 1
fi

branch=$1
userDir="/home/$USER"
domain=""
password=""

shift
while [[ "$#" -gt 0 ]]; do
    case $1 in
        --domain) domain="$2"; shift ;;
        --password) password="$2"; shift ;;
        *) echo "Unknown parameter passed: $1"; exit 1 ;;
    esac
    shift
done

if [ -n "$password" ] && [ -z "$domain" ]; then
  echo "Password option can only be set if domain is set."
fi

# Ensure script is run from a user directory
if [[ $PWD != $userDir ]]; then
  echo "Script must be run from a project user root."
  exit 1
fi

# Create variables
dataDir="$userDir/data"
tarFile="$userDir/artifacts/$branch.tar.gz"
buildNumber=$(openssl rand -hex 8)
destinationBuildDir="$userDir/builds/$branch-$buildNumber"
destinationBranchLink="$userDir/branches/$branch"

# Extract tar.gz file
if [ ! -f "$tarFile" ]; then
  echo "File $tarFile not found"
  exit 1
fi
mkdir -p $destinationBuildDir
if ! tar -xzf $tarFile -C $destinationBuildDir; then
  echo "Failed to extract $tarFile"
  rm -f $tarFile
  exit 1
fi

dotEnv="$destinationBuildDir/.env"
echo "" >> $dotEnv

# Force pasta project name
sed -i '/^PASTA_PROJECT_NAME=/d' $dotEnv
echo "PASTA_PROJECT_NAME=$USER" >> $dotEnv

# Inject build number
echo "PASTA_BUILD=$buildNumber" >> $dotEnv

# Remove virtual host from dot env and force it
if [ -n "$domain" ]; then
  sed -i '/^VIRTUAL_HOST=/d' $dotEnv
  if [[ "$domain" == *"."* ]]; then
    # Has a dot, it's a full-domain
    echo "VIRTUAL_HOST=$domain" >> $dotEnv
  else
    # No dot, it's a sub-domain
    echo "VIRTUAL_HOST=$domain.$PASTA_DOMAIN" >> $dotEnv
  fi
  # Setup password ( or remove it ) and reload proxy
  if [ -n "$password" ]; then
    project-password $projectName $password
    proxy-reload
  fi
fi

# Set the docker compose project name from the unique build number
# With this, "docker compose" commands can be ran from the branch link and the build directory
composeProjectName="$USER_$branch_$buildNumber"
echo "COMPOSE_PROJECT_NAME=$composeProjectName" >> $dotEnv

#echo "USER_ID=$(id -u $USER):$(id -g $USER)" >> $dotEnv

# Preparing data directories
echo "Extracting data directories ..."
dockerComposeConfig=$(cd $destinationBuildDir && docker compose config)
dataVolumes=$(echo "$dockerComposeConfig" | grep "source: $HOME/data" | awk -F"$HOME/data" '{print $2}' | tr -d ' ')

# Create directories for each volume
for volume in $dataVolumes; do
  echo "- $volume"
  mkdir -p "${dataDir}${volume}"
done

# FIXME : Maybe find something else than 777 ?
# FIXME : Adding user to the group is not enough for 776, why ?
# ADD : usermod -aG www-data $username
# REMOVE : gpasswd -d $username www-data
echo "Patching user on data ..."
chown -R "$USER:$USER" $dataDir
chmod -R 0777 $dataDir

# Docker compose up
echo "Starting containers ..."
if ! (cd $destinationBuildDir && docker compose build && docker compose up -d); then
  echo "⚠ Unable to start docker stack"
  rm -rf $destinationBuildDir
  rm -f $tarFile
  exit 1
fi
echo ""

# TODO : Wait enough time to have the new container ready before stopping the old one
# TODO : Maybe having a heartbeat call or something ?
# TODO : If more than 60s, docker compose down and fail
sleep 3

echo "Stopping and removing old containers ..."
if [ -d $destinationBranchLink ]; then
  oldBranchDir=$(readlink -f $destinationBranchLink)
  (cd $oldBranchDir && docker compose down && docker container prune -f)
  rm -rf $oldBranchDir
fi
echo ""

echo "Creating branch link ..."
ln -sf $destinationBuildDir $destinationBranchLink
rm -f $tarFile

echo ""
echo "Done"
