#!/bin/bash

if [ "$#" -lt 1 ]; then
  echo "Usage."
  echo "Add password :"
  echo "project-password.sh <full-domain> <login:password>"
  echo "Remove password :"
  echo "project-password.sh <full-domain>"
  exit 1
fi

domain=$1
loginAndPassword=$2
directory="/root/containers/services/proxy/data/passwords/$domain"
passwordFile="$directory/.htpasswd"

# Remove password
if [ -z "$loginAndPassword" ]; then
  echo "Removing password for $domain ..."
  rm -f $passwordFile
else
  echo "Creating password for $domain ..."
  htpasswd -cb $passwordFile $(echo $loginAndPassword | cut -d: -f1) $(echo $loginAndPassword | cut -d: -f2)
fi

proxy-reload

# TODO :
#- Update imprnncbl server
#- Install outil sur imprnncbl
